// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPVR400f6qOVE66F9CYPziit7WDuL4HA',
    appId: '1:988771255257:android:be9df3625a8c4931d64fc8',
    messagingSenderId: '988771255257',
    projectId: 'deeds-circle',
    storageBucket: 'deeds-circle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsTxxHHVEMvSMRYiOFtroEBzTlnqj2Zg',
    appId: '1:988771255257:ios:271a96dfcd009353d64fc8',
    messagingSenderId: '988771255257',
    projectId: 'deeds-circle',
    storageBucket: 'deeds-circle.firebasestorage.app',
    iosBundleId: 'com.example.deedsCircle',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Sn7ZnLbmPpIMKjdnmo-jXrrqzFu-lB4',
    appId: '1:988771255257:web:5a78065bed60aa63d64fc8',
    messagingSenderId: '988771255257',
    projectId: 'deeds-circle',
    authDomain: 'deeds-circle.firebaseapp.com',
    storageBucket: 'deeds-circle.firebasestorage.app',
    measurementId: 'G-YL4B0BBGVW',
  );

}